version: "2"
volumes: 
  db:
services:
  authservice:
    build: .
    environment: 
    - NODE_ENV=production
    ports:
    - "4000:4000"
    depends_on:
    - mongodb
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    volumes: 
    - db:/data/db

networks: 
  default:
    external: 
      name: todo